[genesis]
fileName = "genesis.json"
network = "test"
extraData = "Kowala's first block!"

[genesis.governance]
origin = "0x259be75d96876f2ada3d202722523e9cd4dd917d"
governors = ["0xa1e8587ed7f915d5bbbf283b21af4813232069f7", "0xbfAdCF85554F139F978DE5442aacFBe085c754f7", "0xF358eb1020375800746ccd5c6638DA36C5a6bec9"]
numConfirmations = 2

[genesis.consensus]
engine = "tendermint" 
maxNumValidators = 100
freezePeriod = 1
baseDeposit = 1000000
[[genesis.consensus.validators]]
address = "0xf1d07c7c551c9a441154675a2b87b228a521f9b9"
deposit = 1000000

[genesis.consensus.token]
name = "mUSD"
symbol = "mUSD"
cap = 1073741824
decimals = 18
[[genesis.consensus.token.holders]]
address = "0xf1d07c7c551c9a441154675a2b87b228a521f9b9"
numTokens = 1000000

[genesis.datafeed]
maxNumOracles = 1000
freezePeriod = 1
baseDeposit = 10

[[prefundedAccounts]]
accountAddress = "0xa1e8587ed7f915d5bbbf283b21af4813232069f7"
balance = 50

[[prefundedAccounts]]
accountAddress = "0xbfAdCF85554F139F978DE5442aacFBe085c754f7"
balance = 50

[[prefundedAccounts]]
accountAddress = "0xF358eb1020375800746ccd5c6638DA36C5a6bec9"
balance = 50