site_name: kCoin Documentation
dev_addr: 0.0.0.0:8000
theme:
  name: material
  favicon: 'https://cdn.kowala.tech/images/meta/favicon.ico'
  logo: 'https://cdn.kowala.tech/images/kowala/kowala-white.svg'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/kowala-tech'
    - type: 'twitter'
      link: 'https://twitter.com/KowalaTech'
    - type: 'youtube'
      link: 'https://www.youtube.com/channel/UCDuyhBaLx16iEGwqIt9hHHQ/'
    - type: 'telegram'
      link: 'https://t.co/MpSK3z1aWw'
    - type: 'facebook'
      link: 'https://www.facebook.com/kowalatech/'
    - type: 'reddit'
      link: 'https://www.reddit.com/user/kowalatech'
site_url: https://docs.kowala.tech
repo_url: https://github.com/kowala-tech/kcoin
repo_name: kowala-tech/kcoin
extra_css:
    - assets/stylesheets/style.css
pages:
  - 'Home': 'index.md'
  - Project:
    - 'Overview': 'project/overview.md'
    - 'Roadmap': 'project/roadmap.md'
  - Getting Started:
    - 'Overview': 'getting-started/index.md'
    - 'Download KClient' : 'getting-started/download.md'
    - 'Join the Test Network' : 'getting-started/testnet.md'
    - 'Validator Registry': 'getting-started/consensus.md'
  - Glossary: 'glossary/index.md'
  - Consensus:
    - 'Overview': 'consensus/index.md'
    - 'Kowala Protocol': 'consensus/kowala.md'
    - 'Proof-of-Stake Pitfalls': 'consensus/pitfalls.md'
    - 'Network Safety': 'consensus/safety.md'
    - 'Algorithm': 'consensus/algorithm.md'
  - Oracle:
    - 'Overview': 'oracle/index.md'
  - Advanced:
    - Core Types:
      - 'Block':  'advanced/types/block.md'
      - 'Transaction': 'advanced/types/tx.md'
      - 'Account': 'advanced/types/account.md'
  - Contributing:
    - 'Projects': 'contributing/projects.md'
  - About:
    - 'Support': 'about/support.md'
copyright: If you wish to improve the documentation, please <a href="https://github.com/kowala-tech/kcoin/issues/new"><i class="fa fa-github"></i> open an issue</a> and <a href="https://github.com/kowala-tech/kcoin/compare"><i class="fa fa-github"></i> send a pull request</a>.<br> Docs v0.0.1. Kowala SEZC 2018.
